### ISSUE TITLE
Generate API docs

### ISSUE THREAD

**Issue by ajpetersons** [loadero/loadero-python#5]
Should be great to generate the first API doc from code to see how it looks from the user perspective. 
Got some insight from the /tests, but since it is too long for Readme, maybe a separate html Wiki page generated with [Doxygen](https://www.doxygen.nl/index.html)

_Originally posted by @merinsTDL in https://github.com/loadero/loadero-python/pull/4#discussion_r847609710_

**Comment by ruzv** [comment]
done https://loadero.github.io/loadero-python/
